ruby-init: Add -d argument to create a directory

diff --git a/bin/ruby-init b/bin/ruby-init
--- a/bin/ruby-init
+++ b/bin/ruby-init
@@ -13,13 +13,19 @@ usage() {
   echo "Usage: $cmd [OPTIONS...] RUBY_VERSION"
   echo
   echo "Options:"
-  echo "  -h    show this help message"
+  echo "  -d DIR      create files in directory DIR"
+  echo "  -h          show this help message"
   echo
-  echo "Example: $cmd 2.6.3"
+  echo "Example: $cmd -d my-project 2.6.3"
 }
 
-while getopts ':h' opt; do
+dest_dir='.'
+
+while getopts ':d:h' opt; do
   case "$opt" in
+    d)
+      dest_dir="$OPTARG"
+      ;;
     h)
       usage
       exit
@@ -30,8 +36,14 @@ while getopts ':h' opt; do
       1>&2 usage
       exit 1
       ;;
+    :)
+      1>&2 echo "Error: Option -$OPTARG is missing an argument"
+      1>&2 echo
+      1>&2 usage
+      ;;
   esac
 done
+shift $((OPTIND -1))
 
 ruby_version=${1:-}
 
@@ -40,9 +52,14 @@ if [ -z "$ruby_version" ]; then
   exit 1
 fi
 
-if [ -e Gemfile ]; then
+if [ -e "${dest_dir}/Gemfile" ]; then
   1>&2 echo "Error: File exists: Gemfile"
   exit 1
+fi
+
+if [ "$dest_dir" != '.' ]; then
+  mkdir -p "$dest_dir"
+  cd "$dest_dir"
 fi
 
 rbenv install --skip-existing "$ruby_version"
